const {test}=require('node:test');const assert=require('node:assert/strict');
test('mutation queue holds failed operation ahead of finish and retry keeps original ID',async()=>{
 const {MutationQueue}=await import('../../web/queue.mjs');let offline=true,calls=[];
 const q=new MutationQueue(async(n,p)=>{calls.push([n,p.clientRequestId]);if(offline)throw Error('offline');return {ok:true};},'u');
 const a=q.add('appendTrack',{points:[1]}),b=q.add('finishRun',{expectedTrackCount:1});await assert.rejects(q.flush(),/offline/);assert.equal(q.pending.length,2);assert.equal(calls.length,1);offline=false;await q.flush();assert.deepEqual(calls.map(x=>x[0]),['appendTrack','appendTrack','finishRun']);assert.equal(calls[0][1],calls[1][1]);assert.notEqual(a.id,b.id);assert.equal(q.pending.length,0);
});
test('account change drops queued personal operations and stale responses cannot drain new queue',async()=>{
 const {MutationQueue}=await import('../../web/queue.mjs');let resolve;const q=new MutationQueue(()=>new Promise(r=>resolve=r),'u');q.add('updateProfile',{displayName:'old'});const f=q.flush();q.setUser('other');q.add('updateProfile',{displayName:'new'});resolve({ok:true});await assert.rejects(f,/ACCOUNT_CHANGED/);assert.equal(q.pending[0].payload.displayName,'new');assert.equal(q.pending.length,1);
});
test('server session adapts timed samples to HTML without joining paused segments',async()=>{const {sessionForHTML}=await import('../../web/state-adapter.mjs');const s=sessionForHTML({id:'x',mode:'RUN',courseId:'c1',startedAt:1000,endedAt:5000,activeMs:2000,status:'COMPLETED',distanceM:10,track:[{lat:37,lng:127,acc:8,recordedAt:1000,t:1000,segment:0},{lat:37,lng:127.001,acc:8,recordedAt:2000,t:2000,segment:1}],pauses:[{from:2000,to:4000}],metrics:{splits:[],pauseMs:2000}});assert.equal(s.segs.length,0,"Isolated points across a pause must not form drawable legs");assert.equal(s.samples[1].gap,true);assert.equal(s.samples[1].t,1000);assert.equal(s.pauseMs,2000);assert.equal(s.sim,false);});
test('queue restores failed GPS under same owner and removes persisted data on account switch',async()=>{const {MutationQueue}=await import('../../web/queue.mjs');const memory=new Map(),storage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};const q=new MutationQueue(async()=>{throw Error('offline')},'u',storage);const op=q.add('appendTrack',{points:[{lat:37,lng:127}]});await assert.rejects(q.flush());const restored=new MutationQueue(async()=>({ok:true}),'u',storage);assert.equal(restored.pending[0].id,op.id);await restored.flush();assert.equal(new MutationQueue(()=>{},'u',storage).pending.length,0);restored.add('appendTrack',{points:[1]});restored.setUser('other');assert.equal(new MutationQueue(()=>{},'u',storage).pending.length,0);});
test('discard selectively clears persisted expired session operations',async()=>{const {MutationQueue}=await import('../../web/queue.mjs');const q=new MutationQueue(()=>{},'u');q.add('appendTrack',{sessionId:'old',points:[1]});q.add('appendTrack',{sessionId:'new',points:[2]});q.remove(o=>o.payload.sessionId==='old');assert.equal(q.pending.length,1);assert.equal(q.pending[0].payload.sessionId,'new');});
test('committed mutation survives refresh failure; ambiguous network retry keeps ID',async()=>{const {commit}=await import('../../web/operations.mjs');const requests=new Map();let first=true,calls=[];const invoke=async(n,p)=>{calls.push(p.clientRequestId);if(first){first=false;throw Error('offline')}return {ok:true,status:'COMPLETED'}};await assert.rejects(commit(invoke,requests,'finishRun',{sessionId:'s'},()=>{},()=>{}),/offline/);const result=await commit(invoke,requests,'finishRun',{sessionId:'s'},async()=>{throw Error('refresh offline')},()=>{});assert.equal(result.status,'COMPLETED');assert.equal(calls[0],calls[1]);assert.equal(requests.size,0);});
test('failed capture seal can retry the identical capture payload before upload',async()=>{const {ensureSealed}=await import('../../web/capture.mjs');const ticket={id:'t',sealData:{ticketId:'t',loc:{measuredAt:100}}};let calls=0;const seal=async p=>{assert.equal(p.loc.measuredAt,100);if(++calls===1)throw Error('offline');return {ok:true};};await assert.rejects(ensureSealed(ticket,seal),/offline/);await ensureSealed(ticket,seal);assert.equal(ticket.sealed,true);await ensureSealed(ticket,seal);assert.equal(calls,2);});
test('only the latest refresh response may publish its snapshot',async()=>{const {RefreshGate}=await import('../../web/refresh-gate.mjs');const gate=new RefreshGate(),first=gate.start(),second=gate.start();assert.equal(first(),false);assert.equal(second(),true);gate.invalidate();assert.equal(second(),false);});

test('version3 news separates published source dates from team checking and never invents checking',async()=>{const {newsForHTML}=await import('../../web/contract-adapter.mjs');const a=newsForHTML({createdAt:1000,date:'2024-01-01',dateKind:'회의일',source:'구의회 회의록'});assert.equal(a.pub,'2024-01-01');assert.equal(a.pubKind,'회의일');assert.equal(a.checked,null);assert.equal(a.kind,'council');const b=newsForHTML({createdAt:1000,pub:null,date:'2024-01-01',checked:'2026-10-05'});assert.equal(b.pub,null);assert.equal(b.checked,'2026-10-05');});
test('captured participation retains its original or explicitly absent session across later starts',async()=>{const {participationPayload}=await import('../../web/contract-adapter.mjs');assert.equal(participationPayload({sessionId:'old'},'new').sessionId,'old');assert.equal(participationPayload({sessionId:null},'new').sessionId,null);assert.equal(participationPayload({},'new').sessionId,'new');});
test('version3 results expose server partial laps, track quality and never draw invalid GPS joins',async()=>{const {sessionForHTML}=await import('../../web/state-adapter.mjs');const s=sessionForHTML({startedAt:0,activeMs:200000,distanceM:1200,metrics:{observedMs:100000,splits:[{index:1,distanceM:1000,durationMs:300000,partial:false},{index:2,distanceM:200,durationMs:60000,partial:true}]},track:[{lat:37,lng:127,acc:5,recordedAt:0,segment:0},{lat:37.0001,lng:127,acc:5,recordedAt:10000,segment:0},{lat:38,lng:127,acc:5,recordedAt:20000,segment:0},{lat:37.0002,lng:127,acc:5,recordedAt:30000,segment:0},{lat:37.0003,lng:127,acc:5,recordedAt:40000,segment:0}]});assert.deepEqual(s.laps.map(x=>x.distM),[1000,200]);assert.equal(s.laps[1].partial,true);assert.equal(s.quality.incomplete,true);assert.equal(s.segs.length,2);assert.equal(s.segs[0].length,2);assert.equal(s.segs[1].length,2);assert.equal(sessionForHTML({startedAt:0,distanceM:0,activeMs:1000,track:[]}).quality.noDistance,true);});
