const {connect,project,number}=require('./cloud-client.cjs');
(async()=>{const c=await connect(),iam=c('https://iam.googleapis.com','v1'),crm=c('https://cloudresourcemanager.googleapis.com','v1'),email=`uirun-runtime@${project}.iam.gserviceaccount.com`;try{await iam.get(`projects/${project}/serviceAccounts/${email}`);}catch(e){if(e.status!==404)throw e;await iam.post(`projects/${project}/serviceAccounts`,{accountId:'uirun-runtime',serviceAccount:{displayName:'UIRUN Functions runtime'}});}
 const policy=(await crm.post(`projects/${project}:getIamPolicy`,{options:{requestedPolicyVersion:3}})).body;
 require('./storage-rules-iam.cjs').ensureStorageRulesBinding(policy,number);
 const grants=[['roles/datastore.user',email],['roles/firebaseauth.admin',email],['roles/eventarc.eventReceiver',email],['roles/run.invoker',email],['roles/pubsub.publisher',`service-${number}@gs-project-accounts.iam.gserviceaccount.com`],['roles/iam.serviceAccountTokenCreator',`service-${number}@gcp-sa-pubsub.iam.gserviceaccount.com`]];
 for(const[role,sa]of grants){let b=policy.bindings.find(b=>b.role===role&&!b.condition);if(!b){b={role,members:[]};policy.bindings.push(b);}if(!b.members.includes('serviceAccount:'+sa))b.members.push('serviceAccount:'+sa);}
 await crm.post(`projects/${project}:setIamPolicy`,{policy});
 const saPath=`projects/${project}/serviceAccounts/${email}`;const saPolicy=(await iam.post(`${saPath}:getIamPolicy`,{})).body;saPolicy.bindings=saPolicy.bindings||[];if(!saPolicy.bindings.some(b=>b.role==='roles/iam.serviceAccountTokenCreator'&&b.members.includes('serviceAccount:'+email)))saPolicy.bindings.push({role:'roles/iam.serviceAccountTokenCreator',members:['serviceAccount:'+email]});await iam.post(`${saPath}:setIamPolicy`,{policy:saPolicy});
 const storage=c('https://storage.googleapis.com');const bucket=`${project}.firebasestorage.app`;const bp=(await storage.get(`/storage/v1/b/${bucket}/iam`)).body;let b=bp.bindings.find(b=>b.role==='roles/storage.objectAdmin'&&!b.condition);if(!b){b={role:'roles/storage.objectAdmin',members:[]};bp.bindings.push(b);}if(!b.members.includes('serviceAccount:'+email))b.members.push('serviceAccount:'+email);await storage.put(`/storage/v1/b/${bucket}/iam`,bp);console.log('UIRUN runtime and event service-agent permissions configured');})().catch(e=>{console.error(e.message);process.exitCode=1});
