const V=require('./validation'),sharp=require('sharp');
function rectangles(input=[]){if(!Array.isArray(input)||input.length>50)V.fail('INVALID_ARGUMENT');return input.map(r=>{if(!r||typeof r!=='object')V.fail('INVALID_ARGUMENT');const x=V.number(r.x,0,1),y=V.number(r.y,0,1),width=V.number(r.width,.001,1),height=V.number(r.height,.001,1);if(x+width>1||y+height>1)V.fail('INVALID_ARGUMENT');return{x,y,width,height}})}
function eligible(d,p,now){const i=d.issues[p?.issueId],o=d.obs[p?.observationId];return !!p&&p.status==='READY'&&now-(p.createdAt||0)<=90*86400000&&!d.deletionJobs[p.uid]&&i?.visibility==='PUBLIC'&&['OPEN','CLOSED','RESOLVED'].includes(i.lifecycleStatus||'OPEN')&&!d.deletionJobs[i.creatorUid]&&o?.visibility!=='HIDDEN'&&!!o&&!o.late;}
function access(d,id,now=Date.now()){const p=d.photos[id];if(!eligible(d,p,now)||p.publicApproved!==true||!p.publicPath)V.fail('NOT_FOUND');const o=d.obs[p.observationId];return{id:p.id,path:p.publicPath,takenAt:p.capturedAt,acceptedAt:o.acceptedAt||o.observedAt,publishedAt:p.publicPublishedAt};}
function forIssue(d,id,now=Date.now()){const p=Object.values(d.photos).filter(p=>p.issueId===id&&eligible(d,p,now)&&p.publicApproved&&p.publicPath).sort((a,b)=>b.capturedAt-a.capturedAt)[0];if(!p)return null;const {path,...meta}=access(d,p.id,now);return meta;}
const copyPath=(id,uid,payload)=>`publicCopies/${V.digest(id)}/${V.digest([uid,payload])}.jpg`;
function publish(d,auth,x,now){if(auth.admin!==true)V.fail('PERMISSION_DENIED');if(typeof x.published!=='boolean')V.fail('INVALID_ARGUMENT');const p=Object.hasOwn(d.photos,x.photoId)?d.photos[x.photoId]:null;if(!p)V.fail('NOT_FOUND');if(x.published){if(x.privacyReviewed!==true)V.fail('PRIVACY_REVIEW_REQUIRED');if(!eligible(d,p,now))V.fail('NOT_FOUND');const boxes=rectangles(x.redactions);const next=copyPath(p.id,auth.uid,x);if(p.publicPath&&p.publicPath!==next)p.retiredPublicPaths=[...new Set([...(p.retiredPublicPaths||[]),p.publicPath])];p.publicPath=next;p.publicApproved=true;p.publicPublishedAt=now;p.publicRedactions=boxes;}else{if(p.publicPath)p.retiredPublicPaths=[...new Set([...(p.retiredPublicPaths||[]),p.publicPath])];p.publicApproved=false;p.publicPath=null;}const id=V.digest([auth.uid,x.clientRequestId,'publication']);d.adminAudits[id]={id,uid:auth.uid,action:'setPhotoPublication',photoId:p.id,published:x.published,privacyReviewed:x.privacyReviewed===true,at:now};return{ok:true,photoId:p.id,published:p.publicApproved};}
async function render(input,boxes){const r=rectangles(boxes);const base=await sharp(input).rotate().resize({width:960,height:960,fit:'inside',withoutEnlargement:true}).jpeg().toBuffer();const {width,height}=await sharp(base).metadata();const overlays=await Promise.all(r.map(async b=>{const left=Math.floor(b.x*width),top=Math.floor(b.y*height),w=Math.min(width-left,Math.max(1,Math.ceil(b.width*width))),h=Math.min(height-top,Math.max(1,Math.ceil(b.height*height)));return{left,top,input:await sharp({create:{width:w,height:h,channels:3,background:'#222222'}}).png().toBuffer()}}));return sharp(base).composite(overlays).jpeg({quality:80}).toBuffer();}
module.exports={rectangles,eligible,access,forIssue,copyPath,publish,render};
