import {newsPayload} from './contract-adapter.mjs?v=20261005-r3';
import {createClient} from './firebase-client.mjs?v=20261005-r3';import {allPages} from './state-adapter.mjs?v=20261005-r3';
const client=await createClient(),$=id=>document.getElementById(id),status=msg=>$('status').textContent=msg,requests=new Map();let ready=false;
const task=fn=>async e=>{e?.preventDefault();try{await fn(e);}catch(err){status(err.message||'요청 실패');}};
async function mutate(name,data){if(!ready)throw Error('관리자 권한이 필요해요');const key=JSON.stringify([name,data]),request=requests.get(key)||{...data,clientRequestId:crypto.randomUUID()};requests.set(key,request);const result=await client.invoke(name,request);if(result.ok===false)throw Error(result.errorCode);requests.delete(key);status('서버에 반영했어요');await refresh();}
async function loadIssue(id){const d=await client.invoke('getAdminIssue',{issueId:id});$('review').elements.issueId.value=id;$('detail').textContent=JSON.stringify(d,null,2);$('photos').replaceChildren();for(const p of d.photos||[]){if(p.status!=='READY')continue;await photoControls(p);}}
async function photoControls(p){const access=await client.invoke('getPhotoAccess',{photoId:p.id});const fig=document.createElement('figure'),title=document.createElement('p');title.textContent='사진 '+p.id+' · 공개용 사본 검토';fig.append(title);const img=new Image();img.src=access.url;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d'),boxes=[];const draw=()=>{ctx.drawImage(img,0,0);ctx.fillStyle='#222';for(const b of boxes)ctx.fillRect(b.x*canvas.width,b.y*canvas.height,b.width*canvas.width,b.height*canvas.height)};draw();let start=null;const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}};canvas.onpointerdown=e=>{start=point(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=e=>{if(!start)return;const end=point(e),b={x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),width:Math.abs(end.x-start.x),height:Math.abs(end.y-start.y)};start=null;if(b.width>=.001&&b.height>=.001&&boxes.length<50)boxes.push(b);draw()};const help=document.createElement('p');help.textContent='가릴 얼굴·차량번호 등을 드래그해 선택하세요. 자동 비식별 검사가 아니므로 공개 전 직접 확인해야 합니다.';const check=document.createElement('input');check.type='checkbox';const label=document.createElement('label');label.append(check,document.createTextNode('식별 요소가 없거나 필요한 모든 영역을 가렸는지 확인했습니다.'));const reset=document.createElement('button');reset.textContent='가림 영역 초기화';reset.onclick=()=>{boxes.splice(0);check.checked=false;draw()};const publish=document.createElement('button');publish.textContent='검토한 공개 사본 게시';publish.onclick=task(async()=>{if(!check.checked)throw Error('개인정보 검토를 확인해주세요');await mutate('setPhotoPublication',{photoId:p.id,published:true,privacyReviewed:true,redactions:boxes.map(b=>({...b}))});});const unpublish=document.createElement('button');unpublish.textContent='공개 해제';unpublish.onclick=task(()=>mutate('setPhotoPublication',{photoId:p.id,published:false}));fig.append(help,canvas,label,reset,publish,unpublish);$('photos').append(fig);}
async function refresh(){const rows=await allPages(client.invoke,'getAdminQueue','issues');$('queue').replaceChildren();for(const row of rows){const b=document.createElement('button');b.textContent=`${row.categoryCode} · ${row.verificationLevel} · ${row.id}`;b.onclick=task(()=>loadIssue(row.id));$('queue').append(b);}const q=await client.invoke('getAdminQueue');$('welcome-list').textContent=JSON.stringify(q.welcome||q.pendingWelcome||[],null,2);}
$('load-issue').onclick=task(()=>loadIssue($('review').elements.issueId.value.trim()));
$('login').onclick=task(()=>client.login());$('logout').onclick=task(()=>client.logout());$('reload').onclick=task(refresh);
for(const [id,name]of [['review','adminDecision'],['welcome','approveWelcome']])$(id).onsubmit=task(e=>mutate(name,Object.fromEntries(new FormData(e.target))));
$('publish').onsubmit=task(e=>{const d=Object.fromEntries(new FormData(e.target));d.published=d.published==='true';return mutate('setNewsPublished',d);});
$('merchant').onsubmit=task(async e=>{const d=Object.fromEntries(new FormData(e.target));await mutate('configureMerchant',{id:d.id,name:d.name,pin:d.pin,isDemo:false,catalog:{title:d.title,condition:d.condition,stock:Number(d.stock),validDays:Number(d.validDays)}});e.target.elements.pin.value='';});
$('pilot').onsubmit=task(e=>mutate('configurePilot',JSON.parse(e.target.elements.json.value)));
client.onUser(async user=>{ready=false;$('admin').hidden=true;if(!user){status('관리자 계정으로 로그인해주세요.');return;}try{ready=(await user.getIdTokenResult()).claims.admin===true;if(!ready){status('로그인했지만 관리자 권한이 없어요.');return;}$('admin').hidden=false;await refresh();status('관리자 권한 확인됨');}catch(e){status(e.message);}});

$('news').onsubmit=task(e=>{return mutate('upsertNews',newsPayload(new FormData(e.target)));});

if(client.emulator&&client.config.projectId==='demo-uirun'){$('local-login').hidden=false;$('local-login').onclick=task(async()=>{const {signInWithEmailAndPassword}=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js');await signInWithEmailAndPassword(client.auth,'admin@verification.test','Local-only-12345');});}
