import {newsPayload} from './contract-adapter.mjs?v=20261005-r3';
import {createClient} from './firebase-client.mjs?v=20261005-r3';import {allPages} from './state-adapter.mjs?v=20261005-r3';
const client=await createClient(),$=id=>document.getElementById(id),status=msg=>$('status').textContent=msg,requests=new Map();let ready=false, dashboard=null, issueRows=[], refreshVersion=0;
const task=fn=>async e=>{e?.preventDefault();const buttons=e?.target?.tagName==='FORM'?[...e.target.querySelectorAll('button')]:e?.currentTarget?.tagName==='BUTTON'?[e.currentTarget]:[];buttons.forEach(b=>b.disabled=true);try{await fn(e);}catch(err){status(err.message||'요청 실패');}finally{buttons.forEach(b=>b.disabled=false);}};
async function mutate(name,data){if(!ready)throw Error('관리자 권한이 필요해요');const key=JSON.stringify([name,data]),request=requests.get(key)||{...data,clientRequestId:crypto.randomUUID()};requests.set(key,request);const result=await client.invoke(name,request);if(result.ok===false)throw Error(result.errorCode);requests.delete(key);status('서버에 반영했어요');await refresh();}
async function loadIssue(id){const d=await client.invoke('getAdminIssue',{issueId:id});$('review').elements.issueId.value=id;$('detail').textContent=[`제보: ${d.issue.id}`,`유형: ${d.issue.categoryLabel||d.issue.categoryCode}`,`검증: ${labels[d.issue.verificationLevel]||d.issue.verificationLevel||'검토 대기'}`,`공개 상태: ${d.issue.visibility==='HIDDEN'?'숨김':'공개'}`,`등록일: ${date(d.issue.createdAt)}`,`위치: ${JSON.stringify(d.issue.anchor||{})}`,`첨부 사진: ${(d.photos||[]).length}장`].join('\n');$('photos').replaceChildren();for(const p of d.photos||[]){if(p.status!=='READY')continue;await photoControls(p);}}
async function photoControls(p){const access=await client.invoke('getPhotoAccess',{photoId:p.id});const fig=document.createElement('figure'),title=document.createElement('p');title.textContent='사진 '+p.id+' · 공개용 사본 검토';fig.append(title);const img=new Image();img.src=access.url;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d'),boxes=[];const draw=()=>{ctx.drawImage(img,0,0);ctx.fillStyle='#222';for(const b of boxes)ctx.fillRect(b.x*canvas.width,b.y*canvas.height,b.width*canvas.width,b.height*canvas.height)};draw();let start=null;const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}};canvas.onpointerdown=e=>{start=point(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointerup=e=>{if(!start)return;const end=point(e),b={x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),width:Math.abs(end.x-start.x),height:Math.abs(end.y-start.y)};start=null;if(b.width>=.001&&b.height>=.001&&boxes.length<50)boxes.push(b);draw()};const help=document.createElement('p');help.textContent='가릴 얼굴·차량번호 등을 드래그해 선택하세요. 자동 비식별 검사가 아니므로 공개 전 직접 확인해야 합니다.';const check=document.createElement('input');check.type='checkbox';const label=document.createElement('label');label.append(check,document.createTextNode('식별 요소가 없거나 필요한 모든 영역을 가렸는지 확인했습니다.'));const reset=document.createElement('button');reset.textContent='가림 영역 초기화';reset.onclick=()=>{boxes.splice(0);check.checked=false;draw()};const publish=document.createElement('button');publish.textContent='검토한 공개 사본 게시';publish.onclick=task(async()=>{if(!check.checked)throw Error('개인정보 검토를 확인해주세요');await mutate('setPhotoPublication',{photoId:p.id,published:true,privacyReviewed:true,redactions:boxes.map(b=>({...b}))});});const unpublish=document.createElement('button');unpublish.textContent='공개 해제';unpublish.onclick=task(()=>mutate('setPhotoPublication',{photoId:p.id,published:false}));fig.append(help,canvas,label,reset,publish,unpublish);$('photos').append(fig);}
const labels={NONE:'검토 대기',ADMIN:'관리자 승인',COMMUNITY:'참여 검증',ISSUED:'사용 가능',USED:'사용 완료',EXPIRED:'기간 만료',USE_REQUESTED:'사용 요청',READY:'업로드 완료',FAILED:'처리 실패'};
const date=value=>value?new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
function el(tag,text){const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);return node;}
function table(target,headers,rows){target.replaceChildren();if(!rows.length){const empty=el('p','표시할 데이터가 없습니다.');empty.className='empty';target.append(empty);return;}const t=el('table'),head=el('tr');for(const h of headers)head.append(el('th',h));const thead=el('thead');thead.append(head);t.append(thead);const body=el('tbody');for(const row of rows){const tr=el('tr');for(const value of row){const td=el('td');if(value instanceof Node)td.append(value);else td.textContent=String(value??'—');tr.append(td);}body.append(tr);}t.append(body);target.append(t);}
function renderIssues(){const q=$('search').value.toLowerCase(),filter=$('issue-filter').value;const rows=issueRows.filter(i=>[i.id,i.categoryLabel,i.categoryCode].join(' ').toLowerCase().includes(q)).filter(i=>filter==='all'||(filter==='hidden'?i.visibility==='HIDDEN':filter==='approved'?i.visibility!=='HIDDEN'&&i.verificationLevel!=='NONE':i.visibility==='PUBLIC'&&i.verificationLevel==='NONE'));table($('queue'),['제보 유형','제보 ID','상태','등록일','검토'],rows.map(i=>{const b=el('button','상세 보기');b.onclick=task(()=>loadIssue(i.id));return[i.categoryLabel||i.categoryCode,i.id,i.visibility==='HIDDEN'?'거절·숨김':labels[i.verificationLevel]||i.verificationLevel,date(i.createdAt),b];}));}
async function refresh(){
 if(!ready)return;const version=++refreshVersion;status('Firebase 데이터를 불러오는 중…');
 const first=await client.invoke('getAdminDashboard',{limit:50});
 // Cursors belong to each table; empty tables must not inherit another table's cursor.
 const fetchPage=async(key,cursor)=>(await client.invoke('getAdminDashboard',{limit:50,table:key,cursor}))[key];
 const collectSafe=async key=>{const rows=[...first[key].items];let cursor=first[key].nextCursor;while(cursor){const next=await fetchPage(key,cursor);rows.push(...next.items);cursor=next.nextCursor;}return rows;};
 const [issues,coupons,photos,q]=await Promise.all([collectSafe('issues'),collectSafe('coupons'),collectSafe('photos'),client.invoke('getAdminQueue')]);
 if(!ready||version!==refreshVersion)return;dashboard=first;issueRows=issues;$('metrics').replaceChildren();
 for(const [label,value] of [['검토 대기 제보',first.stats.pendingIssues],['누적 쿠폰 발급',first.stats.coupons],['쿠폰 사용 완료',first.stats.usedCoupons],['업로드 사진',first.stats.photos]]){const tile=el('div');tile.className='metric';tile.append(el('span',label),el('strong',value.toLocaleString('ko-KR')));$('metrics').append(tile);}
 renderIssues();$('coupon-summary').textContent=`누적 발급 ${first.stats.coupons}장 · 사용 완료 ${first.stats.usedCoupons}장 · 사용 가능 ${first.stats.availableCoupons}장`;
 table($('coupon-list'),['쿠폰 ID','발급받은 사용자','혜택 / 제휴처','상태','발급일','만료일'],coupons.map(c=>[c.id,c.displayName,c.title||c.merchantId||c.catalogId,labels[c.status]||c.status,date(c.issuedAt||c.createdAt),date(c.expiresAt)]));
 $('photo-list').replaceChildren();if(!photos.length){const empty=el('p','아직 업로드된 사진이 없습니다.');empty.className='empty';$('photo-list').append(empty);}
 for(const p of photos){const b=el('button');b.className='photo-tile';b.append(el('strong',labels[p.status]||p.status),el('small',p.id),el('small',p.publicApproved?'공개 중':'비공개'),el('small',date(p.createdAt)));b.onclick=task(async()=>{if(p.issueId)await loadIssue(p.issueId);else{$('photos').replaceChildren();if(p.status==='READY')await photoControls(p);}$('photos').scrollIntoView({behavior:'smooth',block:'start'});});$('photo-list').append(b);if(p.status==='READY')client.invoke('getPhotoAccess',{photoId:p.id}).then(a=>{if(!ready||version!==refreshVersion)return;const img=el('img');img.src=a.url;img.alt='업로드 증빙 사진';img.loading='lazy';b.prepend(img);}).catch(()=>b.append(el('small','미리보기 실패 · 클릭하여 다시 확인')));}
 $('welcome-list').textContent=q.welcome?.length?JSON.stringify(q.welcome,null,2):'승인 대기 중인 웰컴 혜택이 없습니다.';status('Firebase 연결됨 · 마지막 갱신 '+date(first.updatedAt));
}
$('search').oninput=renderIssues;$('issue-filter').onchange=renderIssues;
$('fixed-login').onsubmit=task(async e=>{const button=$('login');button.disabled=true;button.textContent='로그인 중…';try{const x=Object.fromEntries(new FormData(e.target));const {token}=await client.invoke('adminLogin',{id:x.id,password:x.password});const {signInWithCustomToken,setPersistence,browserSessionPersistence}=await import('https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js');await setPersistence(client.auth,browserSessionPersistence);await signInWithCustomToken(client.auth,token);e.target.elements.password.value='';}finally{button.disabled=false;button.textContent='로그인';}});
$('load-issue').onclick=task(()=>loadIssue($('review').elements.issueId.value.trim()));
$('logout').onclick=task(()=>client.logout());$('reload').onclick=task(refresh);
for(const [id,name]of [['review','adminDecision'],['welcome','approveWelcome']])$(id).onsubmit=task(e=>mutate(name,Object.fromEntries(new FormData(e.target))));
$('publish').onsubmit=task(e=>{const d=Object.fromEntries(new FormData(e.target));d.published=d.published==='true';return mutate('setNewsPublished',d);});
$('merchant').onsubmit=task(async e=>{const d=Object.fromEntries(new FormData(e.target));await mutate('configureMerchant',{id:d.id,name:d.name,pin:d.pin,isDemo:false,catalog:{title:d.title,condition:d.condition,stock:Number(d.stock),validDays:Number(d.validDays)}});e.target.elements.pin.value='';});
$('pilot').onsubmit=task(e=>mutate('configurePilot',JSON.parse(e.target.elements.json.value)));
let poll=null;
client.onUser(async user=>{ready=false;refreshVersion++;clearInterval(poll);$('admin').hidden=true;$('login-panel').hidden=false;$('logout').hidden=true;if(!user){status('관리자 계정으로 로그인해주세요.');return;}try{ready=user.uid==='uirun-fixed-admin'&&(await user.getIdTokenResult()).claims.admin===true;if(!ready){status('이 관리자 화면에 접근할 수 없는 계정입니다.');await client.logout();return;}$('admin').hidden=false;$('login-panel').hidden=true;$('logout').hidden=false;await refresh();poll=setInterval(()=>{if(document.visibilityState==='visible')refresh().catch(e=>status('데이터 갱신 실패 · '+e.message));},30000);}catch(e){status(e.message);}});

$('news').onsubmit=task(e=>{return mutate('upsertNews',newsPayload(new FormData(e.target)));});
