import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,connectAuthEmulator,signInWithEmailAndPassword} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFunctions,connectFunctionsEmulator,httpsCallable} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-functions.js';
import {getStorage,connectStorageEmulator,ref,uploadBytes} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-storage.js';
import {verify} from './scenarios.mjs';
if(!/^(localhost|127\.0\.0\.1)$/.test(location.hostname))throw Error('LOCAL_ONLY');
let report;const button=document.querySelector('#run'),summary=document.querySelector('#summary');
button.onclick=async()=>{button.disabled=true;document.querySelector('#results').replaceChildren();summary.textContent='테스트 환경을 준비하는 중…';document.querySelector('#download').disabled=true;document.querySelector('#report-json')?.remove();report=null;try{const prepared=await fetch('/verification/prepare',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!prepared.ok)throw Error('테스트 환경 준비 실패. 에뮬레이터와 verification/server.cjs 실행 상태를 확인해 주세요.');summary.textContent='Web SDK 로그인 및 검증 중…';const clients={};for(const role of ['public','admin','user','peer']){const app=initializeApp({projectId:'demo-uirun',apiKey:'demo-key',storageBucket:'demo-uirun.appspot.com'},role+'-'+Date.now());const auth=getAuth(app),f=getFunctions(app,'asia-northeast3'),storage=getStorage(app);connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});connectFunctionsEmulator(f,'127.0.0.1',5001);connectStorageEmulator(storage,'127.0.0.1',9199);if(role!=='public')await signInWithEmailAndPassword(auth,role+'@verification.test','Local-only-12345');clients[role]={uid:auth.currentUser?.uid,call:async(n,d)=>(await httpsCallable(f,n)(d)).data,upload:(p,b)=>uploadBytes(ref(storage,p),b,{contentType:'image/jpeg'})}}
const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='#ccc';ctx.fillRect(0,0,64,64);const jpeg=await new Promise(r=>canvas.toBlob(r,'image/jpeg'));const contracts=await fetch('/docs/api/contracts.json').then(r=>r.json());let pass=0,fail=0;
report=await verify({clients,jpeg,contracts,emit:row=>{row.status==='PASS'?pass++:fail++;summary.textContent=`진행 중 · 통과 ${pass} · 실패 ${fail}`;const tr=document.createElement('tr');for(const text of [row.label,row.status]){const td=document.createElement('td');td.textContent=text;td.className=row.status;tr.append(td)}const td=document.createElement('td'),details=document.createElement('details'),s=document.createElement('summary'),pre=document.createElement('pre');s.textContent=row.error||'응답 보기';pre.textContent=JSON.stringify(row.result||{error:row.error},null,2);details.append(s,pre);td.append(details);tr.append(td);document.querySelector('#results').append(tr)}});summary.textContent=`완료 · 통과 ${report.pass} · 실패 ${report.fail} · API ${report.called.length}/${contracts.apis.length}`;document.querySelector('#download').disabled=false;
const pre=document.createElement('pre');pre.id='report-json';pre.hidden=true;pre.textContent=JSON.stringify(report);document.body.append(pre);
}catch(e){summary.textContent='검증 중단: '+e.message}finally{button.disabled=false}};
document.querySelector('#download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download='uirun-api-verification.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
