import {checkResponse} from './response-contract.mjs';
export async function verify({clients,jpeg,contracts,emit}) {
 const rows=[];const called=new Set();const assert=(v,msg='Contract assertion failed')=>{if(!v)throw Error(msg)};
 async function step(label,fn){try{const result=await fn();rows.push({label,status:'PASS',result});}catch(e){rows.push({label,status:'FAIL',error:e.message});}emit(rows.at(-1));return rows.at(-1).result}
 async function call(role,name,data={},expected){called.add(name);const c=contracts.apis.find(a=>a.name===name);assert(c,'Undocumented API '+name);if(c.kind==='mutation')data={clientRequestId:crypto.randomUUID(),...data};try{const value=await clients[role].call(name,data);if(expected){assert(value.ok===false&&value.errorCode===expected,'Expected '+expected+', got '+JSON.stringify(value));return {expected}}if(value.ok===false)throw Error(value.errorCode);return checkResponse(name,value,c.kind)}catch(e){if(expected&&e.message===expected)return{expected};throw e}}
 const loc=(lat=37.62)=>({lat,lng:127.05,accuracyM:8,measuredAt:Date.now(),precise:true});
 await step('운영자: 파일럿 경로·코스·정기관찰 등록',()=>call('admin','configurePilot',{paths:[{id:'L',corridorId:'W',points:[[37.619,127.05],[37.623,127.05]]}],courses:[{id:'C',name:'검증 코스',modes:['RUN','WALK'],out:[[37.619,127.05],[37.623,127.05]]}],routines:[{id:'R',name:'검증 정기관찰',enabled:true,roundHours:6,anchors:[[37.62,127.05]],corridorSegmentId:'W',rounds:{}}],facilities:[]}));
 for(const name of ['getHome','getMapData','getRiverFeed','getPilotData','getWeather','getRoutineDetail'])await step('공개 조회: '+name,()=>call('public',name,name==='getRoutineDetail'?{missionId:'R'}:{}));
 await step('미로그인 기록 조회 차단',()=>call('public','getRecords',{},'UNAUTHENTICATED'));
 for(const role of ['user','peer'])await step(role+' 최신 동의 저장',()=>call(role,'recordConsent',{version:'v2-2026-10',accepted:true}));
 await step('프로필 저장',()=>call('user','updateProfile',{displayName:'API 검증'}));
 await step('수정본3 프로필 30자 저장',async()=>{const x=await call('user','updateProfile',{displayName:'가'.repeat(30)});assert(x.displayName==='가'.repeat(30));return x});
 await step('31자 프로필 거절',()=>call('user','updateProfile',{displayName:'가'.repeat(31)},'INVALID_ARGUMENT'));
 await step('빈 이름 초기화',async()=>{const x=await call('user','updateProfile',{displayName:'  '});assert(x.displayName==='');return x});
 await step('설정 저장',()=>call('user','updateSettings',{uiMode:'SIMPLE',repeatObservationNotifications:false}));
 await step('저장한 설정 재조회',async()=>{const x=await call('user','getSettings');assert(x.uiMode==='SIMPLE');return x});
 await step('일반 사용자 운영자 접근 차단',()=>call('user','getAdminQueue',{},'PERMISSION_DENIED'));
 const run=await step('달리기 시작',()=>call('user','startRun',{mode:'RUN',courseId:'C',loc:loc()}));
 if(run){await step('동시 운동 시작 차단',()=>call('user','startRun',{mode:'WALK',loc:loc()},'ACTIVE_SESSION_EXISTS'));
 await new Promise(r=>setTimeout(r,1100));const payload={sessionId:run.sessionId,clientRequestId:crypto.randomUUID(),points:[{lat:37.62,lng:127.05,accuracyM:8,recordedAt:run.startedAt+1},{lat:37.62001,lng:127.05,accuracyM:8,recordedAt:Date.now()}]};
 await step('GPS 전송',async()=>{const x=await call('user','appendTrack',payload);assert(x.count===2);return x});
 await step('같은 요청 재전송: GPS 중복 없음',async()=>{const x=await call('user','appendTrack',payload);assert(x.count===2);return x});
 await step('같은 ID의 다른 요청 충돌 차단',()=>call('user','appendTrack',{...payload,points:payload.points.slice(0,1)},'REQUEST_CONFLICT'));
 await step('미션 노출',()=>call('user','recordMissionExposure',{sessionId:run.sessionId,loc:loc()}));
 await step('일시정지',()=>call('user','pauseRun',{sessionId:run.sessionId}));await step('재개',()=>call('user','resumeRun',{sessionId:run.sessionId}));
 await step('미동기화 종료 차단',()=>call('user','finishRun',{sessionId:run.sessionId,expectedTrackCount:3},'TRACK_NOT_SYNCED'));
 await step('달리기 종료',async()=>{const x=await call('user','finishRun',{sessionId:run.sessionId,expectedTrackCount:2});assert(x.status==='COMPLETED');return x});
 await step('기록 상세·GPS·페이스',async()=>{const x=await call('user','getRunDetail',{sessionId:run.sessionId});assert(x.track.length===2&&x.metrics);return x});
 await step('타인 운동 기록 차단',()=>call('peer','getRunDetail',{sessionId:run.sessionId},'NOT_FOUND'))}
 const walk=await step('산책 시작',()=>call('user','startRun',{mode:'WALK',loc:loc()}));if(walk)await step('산책 취소',async()=>{const x=await call('user','discardRun',{sessionId:walk.sessionId});assert(x.status==='DISCARDED');return x});
 for(const range of ['week','month','year'])await step('운동 집계 '+range,async()=>{const x=await call('user','getWorkoutStats',{range});assert(x.range===range&&x.timeZone==='Asia/Seoul'&&x.buckets.length==={week:7,month:30,year:12}[range]);return x});
 async function photo(role,purpose,lat,targetId){const t=await call(role,'issueCaptureTicket',{purpose,categoryCode:'LITTER',targetId,loc:loc(lat)});await call(role,'sealCapture',{ticketId:t.ticketId,loc:loc(lat)});await clients[role].upload(t.uploadPath,jpeg);for(let i=0;i<50;i++){const s=await call(role,'getPhotoStatus',{ticketId:t.ticketId});if(s.status==='READY')return t.ticketId;if(s.status==='FAILED')throw Error('Photo processing failed');await new Promise(r=>setTimeout(r,400))}throw Error('Photo readiness timeout')}
 const linked=await step('참여 연결 산책 시작',()=>call('user','startRun',{mode:'WALK',loc:loc()}));
 const issues=[];for(const lat of [37.62,37.6205,37.621]){const issue=await step('JPEG 실제 업로드·처리·사진 제보 '+lat,async()=>{const ticketId=await photo('user','DISCOVERY',lat);const x=await call('user','createIssue',{categoryCode:'LITTER',modality:'PHOTO',ticketId,pin:[lat,127.05],...(linked?{sessionId:linked.sessionId}:{})});assert(x.created===true);return{...x,ticketId}});if(issue){issues.push(issue);await step('운영자 제보 승인 '+lat,()=>call('admin','adminDecision',{issueId:issue.resultId,decision:'APPROVE'}))}}
 if(issues[0]){const id=issues[0].resultId;const photoId=issues[0].ticketId;
 await step('미승인 공개 사진 차단',()=>call('public','getPublicPhotoAccess',{photoId},'NOT_FOUND'));
 await step('일반 사용자 사진 공개 차단',()=>call('user','setPhotoPublication',{photoId,published:true,privacyReviewed:true},'PERMISSION_DENIED'));
 await step('개인정보 검토 미확인 공개 차단',()=>call('admin','setPhotoPublication',{photoId,published:true},'PRIVACY_REVIEW_REQUIRED'));
 await step('운영자 마스킹 공개 사본 생성',()=>call('admin','setPhotoPublication',{photoId,published:true,privacyReviewed:true,redactions:[{x:0,y:0,width:.5,height:1}]}));
 await step('공개 사진 실제 다운로드',async()=>{const a=await call('public','getPublicPhotoAccess',{photoId});assert((await fetch(a.url)).ok);return{photoId,expiresInSec:a.expiresInSec}});
 await step('공개 해제',()=>call('admin','setPhotoPublication',{photoId,published:false}));await step('공개 해제 후 접근 차단',()=>call('public','getPublicPhotoAccess',{photoId},'NOT_FOUND'));
 await step('공개 사본 재승인',()=>call('admin','setPhotoPublication',{photoId,published:true,privacyReviewed:true,redactions:[]}));await step('공개 제보 상세: 개인정보 비노출',async()=>{const x=await call('public','getIssueDetail',{issueId:id});assert(!('creatorUid' in x.issue)&&x.own===false);return x});await step('운영자 제보·사진 목록',()=>call('admin','getAdminIssue',{issueId:id}));await step('본인 사진 접근 URL',async()=>{const x=await call('user','getPhotoAccess',{photoId:issues[0].ticketId});assert(x.expiresInSec===300&&/^https?:/.test(x.url));const res=await fetch(x.url);assert(res.ok,'Photo URL HTTP '+res.status);return{expiresInSec:x.expiresInSec,httpStatus:res.status}});await step('타인 사진 접근 차단',()=>call('peer','getPhotoAccess',{photoId:issues[0].ticketId},'PERMISSION_DENIED'));await step('간단 재확인',()=>call('peer','submitQuick',{issueId:id,loc:loc()}));await step('사진 재확인',async()=>call('peer','submitPhotoRecheck',{issueId:id,ticketId:await photo('peer','RECHECK',37.62,id)}))}
 const quick=await step('간단 새 제보',()=>call('user','createIssue',{categoryCode:'LITTER',modality:'QUICK',pin:[37.622,127.05],loc:loc(37.622)}));if(quick)await step('새 제보의 재확인 집계는 0',async()=>{const x=await call('public','getIssueDetail',{issueId:quick.resultId});assert(x.issue.signalCount===0&&x.issue.signalDayKey===null&&x.issue.todaySignalAccountCount===0);return x.issue});if(quick)await step('내 간단 제보에 사진 추가',async()=>call('user','addDiscoveryPhoto',{issueId:quick.resultId,ticketId:await photo('user','DISCOVERY_PHOTO',37.622,quick.resultId)}));
 await step('정기관찰 사진 참여',async()=>call('user','submitRoutine',{missionId:'R',ticketId:await photo('user','ROUTINE',37.62,'R'),...(linked?{sessionId:linked.sessionId}:{})}));
 if(linked){await step('참여 연결 산책 종료',()=>call('user','finishRun',{sessionId:linked.sessionId,expectedTrackCount:0}));await step('운동별 참여 전체 집계',async()=>{const x=await call('user','getRunDetail',{sessionId:linked.sessionId});assert(x.participationStats.report===3&&x.participationStats.routine===1);assert(x.participations.items.length===4);return x.participationStats})}
 await step('제휴처·쿠폰 재고 구성',()=>call('admin','configureMerchant',{id:'M',name:'로컬 검증 카페',pin:'012345',isDemo:true,catalog:{stock:10,title:'검증 쿠폰',condition:'기여 3회',validDays:30}}));
 await step('환영 혜택 운영자 승인',()=>call('admin','approveWelcome',{userId:clients.user.uid}));
 const coupon=await step('쿠폰 발급',()=>call('user','claimWelcome'));if(coupon){const use=await step('쿠폰 사용창 발급',()=>call('user','requestCouponUse',{couponId:coupon.couponId}));if(use){await step('잘못된 PIN 거절',()=>call('user','confirmCouponUse',{couponId:coupon.couponId,useSessionId:use.useSessionId,pin:'999999'},'INVALID_MERCHANT_PIN'));await step('앞자리 0 PIN 정상 사용',()=>call('user','confirmCouponUse',{couponId:coupon.couponId,useSessionId:use.useSessionId,pin:'012345'}))}}
 await step('뉴스 초안 등록',()=>call('admin','upsertNews',{id:'TEST-NEWS',title:'검증 소식',body:'로컬 테스트',sourceUrl:'https://example.com',topic:'proposal',status:'제안 · 검토 답변',kind:'council',source:'로컬 출처',date:'2026-10-05',dateKind:'회의일',pub:'2026-09-30',pubKind:'회의일',checked:'2026-10-05'}));await step('뉴스 게시',()=>call('admin','setNewsPublished',{id:'TEST-NEWS',published:true}));await step('게시 뉴스 공개 조회',async()=>{const x=await call('public','getRiverFeed');assert(x.news.items.some(n=>n.id==='TEST-NEWS'&&n.topic==='proposal'&&n.dateKind==='회의일'&&n.pub==='2026-09-30'&&n.pubKind==='회의일'&&n.checked==='2026-10-05'));return x});
 for(const name of ['getRecords','getMy','getBenefits','getLedger','getAdminQueue','getDeletionJob'])await step('조회 DTO '+name,()=>call(name==='getAdminQueue'?'admin':'user',name));
 const records=await call('peer','getRecords');const withdrawing=records.participations.items.find(o=>o.photo?.id)||records.participations.items[0];if(withdrawing){if(withdrawing.photo?.id)await step('철회 검증용 공개 사본 승인',()=>call('admin','setPhotoPublication',{photoId:withdrawing.photo.id,published:true,privacyReviewed:true,redactions:[]}));await step('본인 기여 철회',()=>call('peer','withdrawContribution',{observationId:withdrawing.id}));if(withdrawing.photo?.id)await step('기여 철회 후 공개 사진 차단',()=>call('public','getPublicPhotoAccess',{photoId:withdrawing.photo.id},'NOT_FOUND'));}
 await step('계정 삭제 요청',()=>call('peer','deleteMyAccountData',{confirm:true}));await step('삭제 처리 중 상태 조회',async()=>{const x=await call('peer','getDeletionJob');assert(x.status==='PENDING');return x});await step('삭제 처리 중 접근 차단',()=>call('peer','getMy',{},'ACCOUNT_DELETING'));
 const missing=contracts.apis.filter(a=>!called.has(a.name)).map(a=>a.name);await step('API 명세 전체 호출 커버리지',()=>{assert(missing.length===0,'Not called: '+missing.join(','));return{called:called.size,total:contracts.apis.length}});
 return{environment:'demo-uirun / local emulators',finishedAt:new Date().toISOString(),pass:rows.filter(r=>r.status==='PASS').length,fail:rows.filter(r=>r.status==='FAIL').length,called:[...called],missing,rows};
}
